apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: de-ai-08

resources:
- ../../base

commonLabels:
  environment: dev

images:
- name: WAS_IMAGE
  newName: 827913617635.dkr.ecr.us-east-2.amazonaws.com/de-ai-08-devops-tf-eks-auto-dev/was
  newTag: ca8be5e69522
- name: WEB_IMAGE
  newName: 827913617635.dkr.ecr.us-east-2.amazonaws.com/de-ai-08-devops-tf-eks-auto-dev/web
  newTag: ca8be5e69522
